name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

      - name: Run tests (optional)
        run: npm test || echo "No tests yet"

      # 👉 Deployment step (adjust based on your hosting)
      - name: Deploy Backend
        run: echo "Add deploy command for Render/Heroku/Railway here"

  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents:write
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy frontend to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
